# MangoWM modular config
# This file only sources split config files.
# Use ./ for relative paths.

source=./conf.d/env.conf
source=./conf.d/monitors.conf
source=./conf.d/autostart.conf

source=./conf.d/visuals-behavior.conf
source=./conf.d/visuals-appearance.conf
source=./conf.d/input.conf
source=./conf.d/layout.conf

source=./conf.d/keybinds.conf
source=./conf.d/rules.conf
