#!/bin/sh

export EDITOR="nvim"
export TERMINAL="ghostty"
export TERMINAL_PROG="ghostty"
export BROWSER="firefox"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

export XAUTHORITY=/tmp/Xauthority
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
# export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export OLLAMA_MODELS=$XDG_DATA_HOME/ollama/models
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'

export PATH=$PATH:$HOME/.local/bin

export QT_QPA_PLATFORMTHEME=gtk2

# Starting X
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
    exec Hyprland
fi
