# window rules
windowrule=tags:3,appid:^firefox$
windowrule=tags:3,appid:^zen$
windowrule=isfloating:1,appid:^otter-launcher$,width:400,height:400
windowrule=isfloating:1,appid:^floating-term$,width:600,height:400
windowrule=isfloating:1,title:^big-size$,width:1000,height:600

# layer animation style for launcher
layerrule=animation_type_open:zoom,layer_name:otter-launcher
layerrule=animation_type_close:zoom,layer_name:otter-launcher
