# visuals / behavior
blur=0
layer_shadows=0
shadows=0
border_radius=0

# Keep global opacity fully opaque; set terminal opacity in foot config only.
focused_opacity=1.0
unfocused_opacity=1.0

animations=0
layer_animations=0
allow_tearing=0

# drag visuals / behavior
drag_tile_to_tile=1
drag_tile_small=0
dropcolor=0x00000000
